---
- name: Create and manage Podman containers
  hosts: prod
  collections:
    - containers.podman

  vars:
    container_name: "sonarr"
    container_image: "lscr.io/linuxserver/sonarr:latest"
    user: "reika"
    user_group: "reika"

  tasks:
    - name: Create a Podman volume for sonarr data
      podman_volume:
        name: sonarr_data

    - name: Create Podman container (rootless)
      podman_container:
        name: "{{ container_name }}"
        image: "{{ container_image }}"
        labels:
          io.containers.autoupdate: registry
        state: created
        restart_policy: unless-stopped
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "America/Chicago"
        ports:
          - "18989:8989"
        volumes:
          - "sonarr_data:/config:Z"

    - name: Generate systemd unit file for container
      podman_generate_systemd:
        name: "{{ container_name }}"
        new: true
        no_header: true
        dest: "/home/{{ user }}/.config/systemd/user/"

    - name: Ensure container is started and enabled
      systemd:
        name: "container-{{ container_name }}.service"
        scope: user
        daemon_reload: true
        state: started
        enabled: true

