---
- name: Create and manage Podman containers
  hosts: prod
  become: yes

  collections:
    - containers.podman

  vars:
    container_name: "open-webui"
    container_image: "ghcr.io/open-webui/open-webui:ollama"
    user: "reika"
    user_group: "reika"

  tasks:
    - name: Ensure nvidia-container-toolkit is installed
      dnf:
        name: nvidia-container-toolkit
        state: present

    - name: Create a volume for ollama data
      podman_volume:
        name: ollama_data

    - name: Create a volume for open-webui data
      podman_volume:
        name: openwebui_data

    - name: Create Podman container
      podman_container:
        name: "{{ container_name }}"
        image: "{{ container_image }}"
        #user: "1000:1000"
        labels:
          io.containers.autoupdate: registry
        state: created
        restart_policy: unless-stopped
        security_opt:
          - label=disable
        device: "nvidia.com/gpu=all"
        ports:
          - "13889:8080/tcp"
        volumes:
          - "ollama_data:/root/.ollama:z"
          - "openwebui_data:/app/backend/data:z"

    - name: Generate systemd unit file for container
      podman_generate_systemd:
        name: "{{ container_name }}"
        new: true
        no_header: true
        dest: /etc/systemd/system

    - name: Ensure container is started and enabled
      systemd:
        name: "container-{{ container_name }}.service"
        daemon_reload: true
        state: started
        enabled: true

