---
- name: Create and manage Podman containers
  hosts: prod
  become: yes

  collections:
    - containers.podman

  vars:
    container_name: "jupyter"
    container_image: "docker.io/cschranz/gpu-jupyter:v1.7_cuda-12.2_ubuntu-22.04" # GPU enabled Jupyterlab image
    jupyter_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35613738653036643032363536613230626231363733613463613663306132353632616538323634
          3536326631363262353637376462383334653435633066300a393537393739393566303961326639
          65393539393033643733323332346233353435326237356136666331386434626363373263646336
          3930336137363166310a323533653666333130353330303166633939656233623735316232333761
          30343531666663383734356636646139366434346565313562316437313033343330313266643635
          6333343264343734386633653831383637326263333163316565

    user: "reika"
    user_group: "reika"

  tasks:
    - name: Ensure nvidia-container-toolkit is installed
      dnf:
        name: nvidia-container-toolkit
        state: present

    - name: Create Podman container (rootless)
      podman_container:
        name: "{{ container_name }}"
        image: "{{ container_image }}"
        user: "1000:1000"
        labels:
          io.containers.autoupdate: registry
        state: created
        restart_policy: unless-stopped
        security_opt:
          - label=disable
        device: "nvidia.com/gpu=all"
        env:
          GRANT_SUDO: 'yes'
          JUPYTER_ENABLE_LAB: 'yes'
          NB_UID: "1000"
          NB_GID: "1000"
          JUPYTER_TOKEN: "{{ jupyter_token }}"
        ports:
          - "13888:8888/tcp"
        volumes:
          - "/data/documents/Development:/home/jovyan/work:z"

    - name: Generate systemd unit file for container
      podman_generate_systemd:
        name: "{{ container_name }}"
        new: true
        no_header: true
        dest: /etc/systemd/system

    - name: Ensure container is started and enabled
      systemd:
        name: "container-{{ container_name }}.service"
        daemon_reload: true
        state: started
        enabled: true

