---
- name: Fix SELinux context on all Podman shared files and folders
  hosts: prod
  become: yes

  tasks:
    - name: Set SELinux context for files in /data/media
      community.general.sefcontext:
        target: '/data/media(/.*)?'
        setype: container_file_t
        state: present
        reload: yes

    - name: Relabel existing files in /data/media
      command: restorecon -R -v /data/media

    - name: Set SELinux context for files in /data/incoming
      community.general.sefcontext:
        target: '/data/incoming(/.*)?'
        setype: container_file_t
        state: present
        reload: yes

    - name: Relabel existing files in /data/incoming
      command: restorecon -R -v /data/incoming
