---
- name: Remove Podman container and its systemd service
  hosts: prod  # Replace with your target server(s)
  become: yes  # Required for systemd and Podman operations

  collections:
    - containers.podman

  vars:
    container_name: jupyter-gpu  # Replace with the actual container name
    systemd_service_name: container-{{ container_name }}.service

  tasks:
    - name: Stop and disable systemd service (if it exists)
      systemd:
        name: "{{ systemd_service_name }}"
        state: stopped
        enabled: no

    - name: Remove systemd service file (if it exists)
      file:
        path: /etc/systemd/system/{{ systemd_service_name }}
        state: absent

    - name: Stop and remove the Podman container
      podman_container:
        name: "{{ container_name }}"
        state: absent

    - name: Reload systemd
      systemd:
        daemon_reload: true
